spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://database-demo.clw46aqcm7il.ap-northeast-2.rds.amazonaws.com:3306/userData # Database이름 ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: admin
    password: zootopic # 자신의 mysql 비밀번호
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      #ddl-auto: update